### ISSUE TITLE
Do not change \def

### ISSUE THREAD

**Issue by clason** [texworld/blacktex#41]
I know that using plain TeX `\def` is an anti-pattern considered by your source, and normally LaTeX macros should be defined by `\newcommand` instead. However, it is _not_ safe to blindly replace the former with the latter -- for starters, since you can't know whether `\renewcommand` should have been used instead. There are also legitimate uses of `\def`.  Running `blacktex` on such a file will break it.

I would therefore strongly recommend removing this transformation (or at least put it behind a feature flag, default false, with a prominent warning).

In general, it would be good to make `blacktex` more configurable by being able to toggling every single transformation rule separately -- ideally using a `toml` file (`stylua` can serve as a guide here) -- although I am aware that this would be (too) much work.

**Comment by nschloe** [comment]
> In general, it would be good to make blacktex more configurable by being able to toggling every single transformation rule separately -- ideally using a toml file (stylua can serve as a guide here) -- although I am aware that this would be (too) much work.

Definitely a good idea and not too much work. I'll look into this. I'm not sure what I'll do about the defaults yet, but hopefully the configurability should already help you out.

**Comment by nschloe** [comment]
People have different opinions about that. Every change can (and, if the user base is large, will) break workflows.

**Comment by clason** [comment]
True, but as far as I can tell, all other changes are transparent _in the output_. This is the only one that can actually break a file (which is how I stumbled across it).

**Comment by clason** [comment]
(At the risk of beating a dead horse, but just to make it clear: I'm not saying that all other options _should_ be enabled by default; I'm just adding a single data point that they _could_. On the other hand, I _am_ saying that the `\def` transformation is too dangerous and _should not_ be enabled by default.)

**Comment by clbarnes** [comment]
> it would be good to make blacktex more configurable by being able to toggling every single transformation rule separately

I imagine this project was inspired by the python formatter [black](https://github.com/psf/black), whose stated purpose is to be unconfigurable. There are a few exceptions, which blacktex could also have (for this case, the existing comments exception, and so on); just saying that ultimate configurability isn't necessarily a design goal.

**Comment by clason** [comment]
Sure, and that's fine -- my point is just that unlike black (and other code formatters), blacktex also makes changes that affect the _output_. This is something I do not want; I just want the code formatted (comments stripped for submission, mostly). So I'm hoping for a way to disable all such transformations and only apply those that are guaranteed to leave the output unchanged ("minimal mode", if you will).
