### ISSUE TITLE
Source code no longer available in git?

### ISSUE THREAD

**Issue by andrewimeson** [texworld/blacktex#59]
Could you explain your decision to remove tracking the source code in a public repository in 78c1483fc2adf524a895758188044063c7521499 and relicensing new code as "Other/Proprietary License" after v0.6.0?

The version published in PyPI (v0.8.6) only provides a wheel and no source code. Why should we trust it?

**Comment by nschloe** [comment]
I'm reorganizing some of my repos and I'm not sure yet what to do with the code. It's still available free of charge, but closed source. I completely understand if you feel uncomfortable using it and would like to switch to another project.
