### ISSUE TITLE
Enter new license key for texworld

### ISSUE THREAD

**Issue by chenle02** [texworld/blacktex#60]
Hello,

I cannot use the blacktex today. I am asked to input  the license key. Do you have any ideas what I should do? Thanks a lot for your help~!

```
Warning: Unable to find valid license in
- environment variable TEXWORLD_LICENSE_KEY (env var not found), or
- config file /home/l-----/.local/share/texworld/texworld.toml (file not found)
 
Enter enw license key for texworld:

```

**Comment by nschloe** [comment]
I've pushed back the release bit; just update and you should be fine. Will post further details later.

**Comment by chenle02** [comment]
Hello, nschole,

Thank you very much for your prompt help. It works on my laptop without issue. I will test the workstation which had the issue yesterday and let you know.

Thanks a lot~!

Le

**Comment by chenle02** [comment]
I confirm that it works now on my workstation af ter reinstall: `pip3 install -U blacktex`

Thank you very much~!

Le
